### ISSUE TITLE
Use different emoji

### ISSUE THREAD

**Issue by flying-sheep** [Haroenv/no-facebook-emojis#11]
I don’t see the appeal of replacing horrible emoji with [bad emoji](https://eev.ee/blog/2016/04/12/apple-did-not-invent-emoji/) if there are adequate ones around.

**Comment by Haroenv** [comment]
I replaced it with Unicode codepoints, not with images. If you want better emoji then you can fork it and use some image solution you want, like emoji one, or you can install a better font than Apple Color Emoji. Does this answer your question?

**Comment by flying-sheep** [comment]
sorry, misunderstood! what you do is perfect.

**Comment by Haroenv** [comment]
Yep. Screenshot could be clearer that it's actually Unicode and not images.
