### ISSUE TITLE
Put it on the stores

### ISSUE THREAD

**Issue by Haroenv** [Haroenv/no-facebook-emojis#3]
- [x] sign with developer certificate for Safari (@johjakob? @andreasbackx?)
- [x] get a license for Chrome (or ask someone else's)
- [ ] publish on Safari Extension Gallery
- [ ] publish on Chrome Webstore

**Comment by JohJakob** [comment]
> sign with developer certificate for Safari

See [this pull request](https://github.com/Haroenv/no-facebook-emojis/pull/8)
