### ISSUE TITLE
some emojis don't work

### ISSUE THREAD

**Issue by Haroenv** [Haroenv/no-facebook-emojis#9]
- `black heart` falls back to the black heart instead of the red heart

**Comment by ArnaudWeyts** [comment]
is this fixed in e27117c? I'm not 100% positive

**Comment by Haroenv** [comment]
Nope, I don't think anything regarding to this is fixed.

**Comment by Haroenv** [comment]
I'm sorry, misunderstood that that commit was one you did. I'll have to check but I can't reproduce the second and third point.

**Comment by Haroenv** [comment]
Seems like https://github.com/Haroenv/no-facebook-emojis/commit/e27117c365411dc80637be5bfbcc5444b4b783a3 fixed the fallback to dingbats at least
